### ISSUE TITLE
Add search graphql endpoint

### ISSUE THREAD

**Issue by gsterjov** [ARGA-Genomes/arga-backend#3]
Now that we've got a better idea of what the filters might look like we should add a search endpoint that can process them and deliver appropriate results in different views. Some views based on the demo site
- species
- specimen (or occurrence?)
- map

In essence we want a generic way to construct a filter query and then allow endpoints to specify how to aggregate and display those results. This should be relatively straightforward and be generic enough to allow for future views as it is likely to be used quite heavily compared to the other endpoints (collections, browse data homepage, etc)

It is my belief that by focusing a lot of the functionality on this endpoint we can get the flexibility we want as well get a lot of freebies such as caching and component reuse. It would also simplify sharding as the process heavy tasks will almost entirely be contained in search, but I also doubt we'll hit the traffic levels that would require sharding

**Comment by nickdos** [comment]
> • specimen (or occurrence?)

The “table” view on the demo corresponds to “sequence records” (which are equivalent to occurrences in GBIF/ALA systems). So I would say its neither. "Sequence" or "sequence record" is closer...

The term specimen is used quite a bit - its just an occurrence that has a type: `preservedSpecimen`. The ARGA data does not contain specimen data (directly) but there are some fields in the data that provide an identifier for the specimen that the sequence was extracted from. The formatting is all over the place so we're not very close to matching the actual specimen data (in ALA, GBIF) with a sequence record in ARGA.

**Comment by gsterjov** [comment]
ah nice, that makes sense. thanks!
